// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/converter_version.test.ts.

/** The version of the `@rljson/converter` package. */
export const converterVersion = '0.0.59';
